name: Deploy to DigitalOcean
on:
  push:
    branches: [ main ]  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Publish app
      run: dotnet publish -c Release -o ./publish
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          # Commands to deploy your app on the droplet
          # For example:
          cp -R /src/FantasyStockTrader /home/fantasy_stock_trader
          systemctl restart fantasy_stock_trader
