name: Deploy to DigitalOcean
on:
  push:
    branches: [ main ]  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Publish app
      run: dotnet publish src/FantasyStockTrader/FantasyStockTrader.Web.csproj -c Release -o ./publish
      env:
        CI: false
    - name: Copy files to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        source: "publish/*"
        target: "/home/fantasy_stock_trader"
        strip_components: 1
    - name: Restart Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          sudo systemctl restart fantasy_stock_trader
